_target_: method.DifferentialAnalysisConfig

label: differential analysis
name: indentify differences

grouping :
  - condition
  - timepoint

comparison_mode : pairwise

comparisons :
  - [L-Cycloserine_T0, Control_T0]
  - [L-Cycloserine_T2h, Control_T2h]

statistical_test:
  abundances_file_name: prm-scipy
  meanE_or_fracContrib_file_name: KW
  isotopologue_abs_file_name: ""
  isotopologue_prop_file_name: ""

impute_values:
  abundances_file_name: "min"
  meanE_or_fracContrib_file_name: "min/2"
  isotopologue_abs_file_name: ""
  isotopologue_prop_file_name: ""

thresholds:
  padj_threshold: 0.2
  absolute_log2FC_threshold: 3

