_target_: method.DifferentialAnalysisConfig

label: differential analysis
name: Pairwise computation of statistical differences

grouping :
  - condition
  - timepoint

comparison_mode : pairwise
qualityDistanceOverSpan : -0.3
correction_method : "bonferroni"

impute_values:
  abundances_file_name: "min"
  meanE_or_fracContrib_file_name: "min"
  isotopologue_abs_file_name: "min"
  isotopologue_prop_file_name: "min"

statistical_test:
  abundances_file_name: KW
  meanE_or_fracContrib_file_name: KW
  isotopologue_abs_file_name: KW
  isotopologue_prop_file_name: KW

thresholds:
  padj: 0.05
  absolute_log2FC: 1
