_target_: method.DistrFitPlotConfig

label: distribution fitting plot
name: Plot of distribution fitting result(s)

grouping :
  - condition
  - timepoint

qualityDistanceOverSpan : -0.3

impute_values:
  abundances: "min"
  mean_enrichment: "min"
  isotopologues: "min"
  isotopologue_proportions: "min"

