_target_: method.PcaPlotConfig

label: pca-plot
name: Generate Principal Component Analysis plots

pca_split_further:
  - timepoint
  # - condition

draw_ellipses: null # null if none desired, or 'condition' or 'timepoint'
run_iris_demo: False