_target_: method.TimeCourseAnalysisConfig

label: time-course analysis
name: Time wise computation of statistical differences

grouping:
  - condition
  - timepoint

qualityDistanceOverSpan : -0.3
correction_method : "bonferroni"

impute_values:
  abundances: "min"
  mean_enrichment: "min"
  isotopologues: "min"
  isotopologue_proportions: "min"

statistical_test:
  abundances: KW
  mean_enrichment: KW
  isotopologues: KW
  isotopologue_proportions: KW
