hydra:
  job:
    chdir: true
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}/${analysis.dataset.label}-${analysis.method.label}

# check https://hydra.cc/docs/patterns/specializing_config/ for more info about this
defaults:
  - analysis: synthetic_abundance_plot
  - _self_

figure_path: figures
table_path : tables
suffix : cyc1

# Isotopologue Contribution plot configuration
# -----------------------------
width_each_stack : !!float 3
wspace_stacks : !!float 1.1
numbers_size : 13

palette: pastel
x_text: ''
