hydra:
  job:
    chdir: true
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}/${analysis.dataset.label}-${analysis.method.label}

# check https://hydra.cc/docs/patterns/specializing_config/ for more info about this
defaults:
  - analysis: example_diff_abundance_plot
  - _self_

data_path: "/Users/macha/Projects/myDIMet/data/example_diff"
figure_path: figures
output_path: tables
suffix : cyc1

# metabolites to plot:
metabolites_to_plot:
  cell: ["Fructose_1,6-bisphosphate", # in "quotes" because has a comma inside
         L-Lactic_acid, Pyruvic_acid, L-Malic_acid,
         Fumaric_acid, L-Alanine, L-Glutamic_acid,
         L-Glutamine, L-Aspartic_acid]
  med:  [L-Lactic_acid, Pyruvic_acid,
           L-Alanine, L-Asparagine]

# Abundances bars configuration
# -----------------------------
conditions :
 - Control
 - L-Cycloserine

time_sel :
  - T0
  - T2h
barcolor : timepoint
axisx : condition
axisx_labeltilt : 20 # 0 is no tilt
width_each_subfig : 3
wspace_subfigs : 1

# Isotopologue Contribution plot configuration
# -----------------------------
width_each_stack : !!float 3
wspace_stacks : !!float 1.1
numbers_size : 13


# Fractional Contributions lineplot configuration
# -----------------------------
# will run with defaults, see --help


# -----------------------------
# differential analysis
# -----------------------------
grouping :  # see explanation at the  end
  - condition
  - timepoint

comparisons :   # for each pair,last must be control
  - [L-Cycloserine_T0, Control_T0]
  - [L-Cycloserine_T2h, Control_T2h]

statistical_test:
  abundances: prm-scipy
  meanE_or_fracContrib: KW
  isotopologue_abs: null
  isotopologue_prop: KW

thresholds:
  padj: 1
  absolute_log2FC: 0.3


# grouping: column that is a combination of 2 metadata categories,
# new category thus generated, is ready for comparison. Example :
#  Control (a condition) combined with T0 (a timepoint), yields Control_T0
#  L-Cyclo (another condition) combined with T0 (same timepoint) yields L-Cyclo_T0
#  thus now, we are able to compare L-Cyclo_T0 against Control_T0 .

# -------------------- end of config file ---------------------
# NOTE: Metabolograms need a separated configuration file

# Added
palette: pastel
x_text: ''
