# indicate that we want an instance of Dataset created for this config
_target_: data.DatasetConfig

label: example_diff
name: I am example_diff
#if relative : within the data subfolder, if not, use an absolute path
subfolder: example_diff
#within the data subfolder/raw
metadata: metadata

abundances_file_name : rawAbundances
meanE_or_fracContrib_file_name : FracContribution_C
isotopologue_prop_file_name : CorrectedIsotopologues # isotopologue proportions
isotopologue_abs_file_name : IsotopologuesAbs  # isotopologue absolute values

conditions :
  - sgLDHA # first must be control, when several

suffix : ldh1
