# indicate that we want an instance of Dataset created for this config
_target_: data.DatasetConfig

label: synthetic
name: I am a sythetic data example
#if relative : within the data subfolder, if not, use an absolute path
subfolder: synthetic
#within the data subfolder/raw
metadata: metadata

abundances_file_name : rawAbundances
meanE_or_fracContrib_file_name : FracContribution_C
isotopologue_prop_file_name : CorrectedIsotopologues # isotopologue proportions
isotopologue_abs_file_name : IsotopologuesAbs  # isotopologue absolute values

conditions :
 - Control # first must be control
 - L-Cycloserine

suffix : cyc1
