# indicate that we want an instance of Dataset created for this config
_target_: data.DatasetConfig

label: toy1
name: I am toy1
#if relative : within the data subfolder, if not, use an absolute path
subfolder: toy1
# ALWAYS WITHIN THE RAW SUBFOLDER
metadata: metadata_toy1
abundances_file_name : AbundanceCorrected
meanE_or_fracContrib_file_name : MeanEnrichment13C
isotopologue_prop_file_name : IsotopologuesProp # isotopologue proportions
isotopologue_abs_file_name : IsotopologuesAbs  # isotopologue absolute values

conditions :
 - sgLDHA # first must be control



suffix : ldh1
