label: example_diff_abundance_plot
# Abundances bars configuration
# -----------------------------
time_sel :
  - T0
  - T24

defaults:
  - dataset: example_diff
  - method: differential_analysis #abundance_plot
