label: example_diff_abundance_plot
# Abundances bars configuration
# -----------------------------
time_sel :
  - T0
  - T24

defaults:
  - dataset: toy1
  - method: abundance_plot

metabolites_to_plot:
  endo: [Fru1P, Cit]
