label: example_diff_abundance_plot

defaults:
  - dataset: synthetic
  - method: differential_analysis

time_sel :
  - T0
  - T2h

comparison_mode: "pairwise"

comparisons :
  - [[L-Cycloserine, T0], [Control, T0]]
  - [[L-Cycloserine, T2h], [Control, T2h]]

statistical_test:
  abundances_file_name: prm-scipy
  meanE_or_fracContrib_file_name: KW
  isotopologue_abs_file_name:
  isotopologue_prop_file_name:

thresholds:
  padj: 0.2
  absolute_log2FC: 1
