label: example_diff_abundance_plot
# Abundances bars configuration
# -----------------------------

defaults:
  - dataset: synthetic
  - method: abundance_plot

time_sel :
  - T0
  - T2h

## metabolites to plot:
metabolites_to_plot:
  cell: ["Fructose_1,6-bisphosphate", # in "quotes" because has a comma inside
         L-Lactic_acid, Pyruvic_acid, L-Malic_acid,
         Fumaric_acid, L-Alanine, L-Glutamic_acid,
         L-Glutamine, L-Aspartic_acid]
  med:  [L-Lactic_acid, Pyruvic_acid, L-Alanine, L-Asparagine]
